# Generated by Django 4.0.3 on 2022-03-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Skils',
            new_name='Skil',
        ),
    ]
